### ISSUE TITLE
How to select single component from multiple on page

### ISSUE THREAD

**Issue by claytron5000** [abhinaba-ghosh/cypress-react-selector#41] opened 2020-09-09 20:22 UTC
I have a number of `IconButton` components on a page. They are mostly differentiated by where they are on the page, so different parents. can I drill down from a selected parent to child?

**Comment by abhinaba-ghosh** [comment] 2020-09-09 20:30
Hi @claytron5000 , thanks for raising the query. You wanna look into the `chained command` section: https://github.com/abhinaba-ghosh/cypress-react-selector#use-fluent-chained-queries

Let me know if that does not work. I will be happy to dig into that.

**Comment by claytron5000** [comment] 2020-09-09 20:43
That's exactly it. I was getting an error, but I think it was a bad selector. Thanks for the cool tool!

**Comment by abhinaba-ghosh** [comment] 2020-09-09 20:46
Hi @claytron5000, when I created the tool, I actually tested against a smaller set of use cases. It is also possible that the error you are getting is a valid error and I missed to handle that very logic. If you get the error, again and again, I request you to re-open the ticket and help me to get it resolved. 

Thanks a lot again for giving a try with the tool. :)

**Comment by abhinaba-ghosh** [comment] 2020-09-09 20:48
also, not, `fluent` chained commands dot really re-try. I am working on it to get it resolved. 

https://github.com/abhinaba-ghosh/cypress-react-selector/issues/30

**Comment by claytron5000** [comment] 2020-09-09 20:59
Yeah, it looks legit.

cypress.json:
```
{
    "pluginsFile": false,
    "supportFile": false,
    "baseUrl": "http://localhost:8080",
    "env": {
        "cypress-react-selector": {
            "root": "#root"
        }
    }
}
```

Test code:
```
describe("Search input", () => {
	beforeEach(() => {
		cy.visit("/");
		cy.waitForReact();
	});

	context("viewport width === 640", () => {
		it("is visible", () => {
			cy.viewport(640, 1_024);
			cy.react("Search").react("SvgIcon").should("be.visible");
			
		});
	});
});
```
React code:
```
function Search() {
	const classes = useStyles();

	return <Box component="form" width="100%" color="text.secondary">
		<TextField InputProps={{
			startAdornment: <InputAdornment position="start"
			className={classes.inputAdornment}>
				<Box p={1.5}>
					<SearchIcon fontSize="small" />
				</Box>
			</InputAdornment>,
			classes: {
				input: classes.input,
				formControl: classes.formControl,
			},
			disableUnderline: true,
		}}
		className={classes.textField}
		placeholder="Search school, city, state &amp; teams..."
		inputProps={{"aria-label": "search"}} />
	</Box>;
}
```

The `SearchIcon` is a MaterialUI svg icon that's transformed into `SvgIcon`. Here's the component tree screenshot:

![image](https://user-images.githubusercontent.com/5767672/92654279-a0477600-f2bd-11ea-9d0f-cb113fce123e.png)

**Comment by abhinaba-ghosh** [comment] 2020-09-09 21:53
Hey @claytron5000 Thanks for re-opening and for the logs. Would you mind also sharing the cypress window error messages? Screenshot will be enough. I want to see the waiting period and the messages it is producing.

**Comment by claytron5000** [comment] 2020-09-10 12:49
```
Component not found <SvgIcon>


  There can be multiple reasons for it.

  > Check the root is defined as a env parameter (cypress.json config file).

  > If the root is defined correctly, check other parameters - component name, props and state objects

  
  Or, raise an issue with proper code samples here: https://github.com/abhinaba-ghosh/cypress-react-selector/issues
node_modules/cypress-react-selector/src/reactHandler.js:89:1
  87 |       })
  88 |       .catch((err) => {
> 89 |         throw new Error(
     | ^
  90 |           getComponentNotFoundMessage(
  91 |             component,
  92 |             reactOpts.props, 
View stack trace
 Print to console
    at eval (webpack:///node_modules/cypress-react-selector/src/reactHandler.js:89:1)
From previous event:
    at getRet (http://localhost:8080/__cypress/runner/cypress_runner.js:154850:21)
From previous event:
    at Context.thenFn (http://localhost:8080/__cypress/runner/cypress_runner.js:154868:27)
    at Context.then (http://localhost:8080/__cypress/runner/cypress_runner.js:155308:22)
    at Context.<anonymous> (http://localhost:8080/__cypress/runner/cypress_runner.js:168808:22)
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:168241:16)
From previous event:
    at runCommand (http://localhost:8080/__cypress/runner/cypress_runner.js:168220:9)
    at next (http://localhost:8080/__cypress/runner/cypress_runner.js:168366:15)
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:168394:17)
From previous event:
    at next (http://localhost:8080/__cypress/runner/cypress_runner.js:168366:35)
From previous event:
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:168407:38)
From previous event:
    at run (http://localhost:8080/__cypress/runner/cypress_runner.js:168400:20)
    at $Cy.cy.<computed> [as viewport] (http://localhost:8080/__cypress/runner/cypress_runner.js:168852:12)
    at Context.runnable.fn (http://localhost:8080/__cypress/runner/cypress_runner.js:169078:22)
    at callFn (http://localhost:8080/__cypress/runner/cypress_runner.js:103957:22)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:8080/__cypress/runner/cypress_runner.js:103944:8)
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:174727:29)
From previous event:
    at Object.onRunnableRun (http://localhost:8080/__cypress/runner/cypress_runner.js:174715:21)
    at $Cypress.action (http://localhost:8080/__cypress/runner/cypress_runner.js:165051:62)
    at Test.Runnable.run (http://localhost:8080/__cypress/runner/cypress_runner.js:173050:14)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:8080/__cypress/runner/cypress_runner.js:104616:11)
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:104742:13)
    at next (http://localhost:8080/__cypress/runner/cypress_runner.js:104525:15)
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:104535:8)
    at next (http://localhost:8080/__cypress/runner/cypress_runner.js:104437:15)
    at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:104503:6)
    at timeslice (http://localhost:8080/__cypress/runner/cypress_runner.js:98429:28)
```

**Comment by abhinaba-ghosh** [comment] 2020-10-11 21:01
Hi @claytron5000, can you try upgrading to `v2.1.0` and retrying the same commands. I have added some extra retry mechanism recently. Would love to get the feedback.

**Comment by zRealMikeJordan** [comment] 2020-10-23 14:18
@abhinaba-ghosh I'm getting the same issue on version 2.2.0.  

  Error: Component not found **<MyComponent>**
cypress   | 
cypress   | 
cypress   |   There can be multiple reasons for it.
cypress   | 
cypress   |   > Check the root is defined as a env parameter (cypress.json config file).
cypress   | 
cypress   |   > If the root is defined correctly, check other parameters - component name, props and state objects
cypress   | 
cypress   |   
cypress   |   Or, raise an issue with proper code samples here: https://github.com/abhinaba-ghosh/cypress-react-selector/issues
cypress   |       at eval (http://client:3000/__cypress/tests?p=cypress/support/index.js:298:15)

**Comment by abhinaba-ghosh** [comment] 2020-10-27 05:57
@zRealMikeJordan, The library works irrespective of the underlying infrastructure. So, if it is working in your local, not in the docker, there is a high chance that the application under test has been changed. Are you building the react app for production and testing it in the docker? Sometimes, it changes the component names. Try building in `profile` mode and try.

**Comment by zRealMikeJordan** [comment] 2020-10-27 12:36
I found the issue. It was actually that the react build resulted in a tree
of “anonymous” components and so you lib couldn’t find the components I
referenced.

I fixed this by doing a dev build in the container but because react
scripts is so slow I had to put sleep 30; at the beginning to wait for
localhost to become available. A bit hacky so if you know a better way
please let me know. I’m not familiar with profile mode.

**Comment by abhinaba-ghosh** [comment] 2020-10-27 20:46
Hey @zRealMikeJordan , good to know that you figured out the issue. [This](https://gist.github.com/bvaughn/25e6233aeb1b4f0cdb8d8366e54a3977) can help to get some idea about the profiling mode.

**Comment by caseyjhol** [comment] 2020-10-30 21:31
@abhinaba-ghosh Thanks for all of your work on this! Unfortunately, chained commands still aren't working for me. I have two `MenuButton` components on my page; one is inside the `DashboardFooter` component (the one I want to target).

```js
describe("Sidebar", () => {
	beforeEach(() => {
		cy.waitForReact();
	});

	it.only("opens sidebar on click", () => {
		cy.react("DashboardFooter").react("MenuButton").click();
	});
});

```
returns

```
cy.click() can only be called on a single element. Your subject contained 2 elements. Pass { multiple: true } if you want to serially click each element.
```

![image](https://user-images.githubusercontent.com/2874325/97757815-2795b680-1ac3-11eb-9109-9139f72f2560.png)

Only one `MenuButton` is visible at any given time. After investigating further using `.first()` and `.last()`, I confirmed that it's selecting both the visible and the invisible buttons, meaning it's behaving exactly as if I wasn't including `cy.react("DashboardFooter")` at all.

**Cypress v5.5.0**
**cypress-react-selector v2.2.0**
My cypress.json:
```json
{
    "pluginsFile": false,
    "baseUrl": "http://localhost:8080",
    "env": {
        "cypress-react-selector": {
            "root": "#root"
        }
    }
}
```

**Comment by abhinaba-ghosh** [comment] 2020-10-31 09:34
@caseyjhol I will have a look into this.

**Comment by abhinaba-ghosh** [comment] 2020-11-15 12:31
Hi, just catching up on things. I have created [this repository ](https://github.com/abhinaba-ghosh/cypress-react-chain-queries)to reproduce this bug. I am digging in. I will update the progress here.

**Comment by abhinaba-ghosh** [comment] 2020-11-15 12:56
https://github.com/baruchvlz/resq/issues/73

**Comment by baruchvlz** [comment] 2020-11-17 17:42
This issue seems to be related to some changes in the way React attaches the FiberNodes to the elements. The release [RESQ v1.10.0](https://github.com/baruchvlz/resq/tree/v1.10.0) should take care of the not being able to find React error.

Now, as to the chain operations. This is not supported in RESQ and should be handled at a library level. One of the ways to do this, is to do `resq.waitToLoadReact()` on every call of `cy.react`.

**Comment by abhinaba-ghosh** [comment] 2020-11-18 14:14
Thanks for the input @baruchvlz .
Much appreciated. Once the resq release is available, i will update this library to tackle the waitForReact calls.

**Comment by abhinaba-ghosh** [comment] 2020-11-21 07:46
> This not being able to find React issue seems to be related to some changes in the way React attaches the FiberNodes to the elements. The release [RESQ v1.10.0](https://github.com/baruchvlz/resq/tree/v1.10.0) should fix it.
> 
> Now, as to the chain operations. This is not supported in RESQ and should be handled at a library level. One of the ways to do this is to do `resq.waitToLoadReact()` on every call of `cy.react`.

hi @baruchvlz , I have a different thought here. I don’t think you need to call `waitToLoadReact` every time internally in `cy.react` calls. Once React loading established, It will return - `React already loaded`, no matter how many times you run it. Now, in the case where AUT reloads the window, yes, you need to re-establish the react loading, not for all. I successfully manage to chain query by providing incoming `ReactElement` in the `resq$$(component, reactElement)` command for [this react example](https://github.com/abhinaba-ghosh/cypress-react-chain-queries). But, for a different app, it is showing wired behavior and logged here - https://github.com/baruchvlz/resq/issues/76

**Comment by frysztak** [comment] 2020-12-21 13:36
hi @abhinaba-ghosh, have you made any progress on this?

**Comment by abhinaba-ghosh** [comment] 2020-12-23 06:43
@hey @frysztak , we are getting few hiccups for React 17. I will work on this over the upcoming weekend. But, PR is always welcome.

**Comment by frysztak** [comment] 2020-12-23 11:31
@abhinaba-ghosh I'd gladly help, though I'm not sure where to start. could you point me in the right direction?

**Comment by abhinaba-ghosh** [comment] 2020-12-23 13:10
> @abhinaba-ghosh I'd gladly help, though I'm not sure where to start. could you point me in the right direction?

@frysztak You can look into this to get the ground https://github.com/baruchvlz/resq/issues/76

**Comment by frysztak** [comment] 2020-12-29 20:09
hello again @abhinaba-ghosh, I finally took a look at your [repo](https://github.com/abhinaba-ghosh/cypress-react-chain-queries). chained queries don't work for React 16 as well. and seeing that this issue was created before React 17's release - it doesn't seem like it has anything to do with it

**Comment by abhinaba-ghosh** [comment] 2021-11-02 11:36
This is now fixed with https://github.com/abhinaba-ghosh/cypress-react-selector/pull/251

Example - https://github.com/abhinaba-ghosh/cypress-react-chain-queries

**Closed** 2021-11-02 11:37 UTC
Labels: bug
