### ISSUE TITLE
Chained commands doesn't work.

### ISSUE THREAD

**Issue by ahaddad-dia** [abhinaba-ghosh/cypress-react-selector#145] opened 2021-02-15 10:26 UTC
I've already checked the [cases](https://github.com/abhinaba-ghosh/cypress-react-selector/issues/48) where the chained command doesn't work, but it doesn't seem to be that issue here.
![nochain](https://user-images.githubusercontent.com/77851409/107934363-a33f4480-6f88-11eb-9ae7-7289455a29f5.png)

I'm getting the same results with or without the first getReact. If the chain command worked nthNode wouldn't be necessary. The result would be unique.

**Comment by abhinaba-ghosh** [comment] 2021-05-08 09:07
duplicate of #176 

Kindly keep an eye on that ticket. I will update.

**Closed by abhinaba-ghosh** 2021-05-08 09:07 UTC

**Comment by abhinaba-ghosh** [comment] 2021-05-08 09:27
@ahaddad-dia Please try with the latest version of cypress-react-selector.
And, keep in mind, if your aim is to chain`getReact` with a `subject` that returns a DOmM element, then chain it with `react` command -

```
cy.react().getReact().getProps()
```
