### ISSUE TITLE
[cypress-react-selector] not loaded yet when it is

### ISSUE THREAD

**Issue by claytron5000** [abhinaba-ghosh/cypress-react-selector#103] opened 2020-12-04 16:36 UTC
I'm getting the `[cypress-react-selector] not loaded yet` when the cypress console is telling me it has been loaded. 
![image](https://user-images.githubusercontent.com/5767672/101188109-412aa080-3623-11eb-83e7-0b82fe007581.png)
I moved it to a `before` call as well, just in case that was the issue, but it behaves the same.
cypress.json:
```
{
	"pluginsFile": false,
	"baseUrl": "http://localhost:8080",
	"env": {
		"cypress-react-selector": {
		  "root": "#root"
		}
	  }
}
```
The test:
```
beforeEach(() => {
    cy.login();
    cy.waitForReact();
});


describe("On the Account Management", () => {

    
    context("Page", () => {
        it("the form exists", () => {
            cy.visit("http://localhost:8080/app/my-account")
            cy.react("MyAccountPage").should("be", "visible")
        })
    })
});
```

Stack trace:
```
cypress_runner.js:199777 Error: [cypress-react-selector] not loaded yet. did you forget to run cy.waitForReact()?
    at getNodes (http://localhost:8080/__cypress/tests?p=cypress/support/index.js:321:17)
    at resolveValue (http://localhost:8080/__cypress/tests?p=cypress/support/index.js:368:16)
    at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/support/index.js:394:14)
From previous event:
    at getRet (http://localhost:8080/__cypress/runner/cypress_runner.js:155115:20)
From previous event:
    at Context.thenFn (http://localhost:8080/__cypress/runner/cypress_runner.js:155133:23)
    at Context.then (http://localhost:8080/__cypress/runner/cypress_runner.js:155572:21)
    at Context.<anonymous> (http://localhost:8080/__cypress/runner/cypress_runner.js:169999:21)
    at http://localhost:8080/__cypress/runner/cypress_runner.js:169423:15
From previous event:
    at runCommand (http://localhost:8080/__cypress/runner/cypress_runner.js:169402:8)
    at next (http://localhost:8080/__cypress/runner/cypress_runner.js:169548:14)
    at http://localhost:8080/__cypress/runner/cypress_runner.js:169576:16
From previous event:
    at next (http://localhost:8080/__cypress/runner/cypress_runner.js:169548:34)
From previous event:
    at Promise.catch.err.name (http://localhost:8080/__cypress/runner/cypress_runner.js:169589:37)
From previous event:
    at run (http://localhost:8080/__cypress/runner/cypress_runner.js:169582:21)
    at $Cy.cy.<computed> [as visit] (http://localhost:8080/__cypress/runner/cypress_runner.js:170039:11)
    at Context.runnable.fn (http://localhost:8080/__cypress/runner/cypress_runner.js:170263:21)
    at callFn (http://localhost:8080/__cypress/runner/cypress_runner.js:104396:21)
    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:8080/__cypress/runner/cypress_runner.js:104383:7)
    at http://localhost:8080/__cypress/runner/cypress_runner.js:175798:28
From previous event:
    at Object.onRunnableRun (http://localhost:8080/__cypress/runner/cypress_runner.js:175786:17)
    at $Cypress.action (http://localhost:8080/__cypress/runner/cypress_runner.js:166429:28)
    at Test.Runnable.run (http://localhost:8080/__cypress/runner/cypress_runner.js:174172:13)
    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (http://localhost:8080/__cypress/runner/cypress_runner.js:105055:10)
    at http://localhost:8080/__cypress/runner/cypress_runner.js:105181:12
    at next (http://localhost:8080/__cypress/runner/cypress_runner.js:104964:14)
    at http://localhost:8080/__cypress/runner/cypress_runner.js:104974:7
    at next (http://localhost:8080/__cypress/runner/cypress_runner.js:104876:14)
    at http://localhost:8080/__cypress/runner/cypress_runner.js:104942:5
    at timeslice (http://localhost:8080/__cypress/runner/cypress_runner.js:98868:27)
```

**Comment by abhinaba-ghosh** [comment] 2020-12-04 20:06
Hi @claytron5000 , thanks for pointing this out. Can you let me know which version of `cypress-react-selector` you are using?

**Comment by claytron5000** [comment] 2020-12-05 17:03
2.2.1

**Comment by davidnaas** [comment] 2020-12-10 11:13
I had this issue as well and the problem is that you're calling `cy.visit` after having checked for react. This will cause a hard refresh which requires you to do wait for react to load again.

I believe this should be pointed out in the docs. It's not necessarily enough to wait for react in the `before` callback but should be done anytime your loading the whole page

**Comment by abhinaba-ghosh** [comment] 2020-12-10 13:12
Good catch @davidnaas . Love to get a PR. 
We basically inject the `resq` object in the window instance so, if `window` gets loaded, you need to call `waitForReact()`.

**Comment by davidnaas** [comment] 2020-12-11 15:41
> Good catch @davidnaas . Love to get a PR.
> We basically inject the `resq` object in the window instance so, if `window` gets loaded, you need to call `waitForReact()`.

Done! #109

**Comment by abhinaba-ghosh** [comment] 2020-12-13 17:54
@davidnaas Merged thanks.

**Closed by abhinaba-ghosh** 2020-12-13 17:54 UTC
Labels: discussion
