### ISSUE TITLE
Not able to find component- Multiple reasons

### ISSUE THREAD

**Issue by aditya-3008** [abhinaba-ghosh/cypress-react-selector#58] opened 2020-10-08 10:34 UTC
Hi Abhinaba,

I have updated my Cypress.json file with the env for cypress-react-selector. I am getting error, while inspecting Component using React-Dev tool. Multiple reasons error. 

Component not found <* name="tradition">

  There can be multiple reasons for it.

  > Check the root is defined as a env parameter (cypress.json config file).

  > If the root is defined correctly, check other parameters - component name, props and state objects

 cy.waitForReact();
      const btn = cy.react('Anonymous*', { props: { name: 'abc' } });
       //const btn = cy.react('CatalogGridItem*', { props: { name: 'xyz' } });
      btn.click();

I am writing End to end tests and doesn't have access to source code, so is there any way to get the component name from React dev tool which I can use in my test scripts using Cyrpess-react-selector.

**Comment by abhinaba-ghosh** [comment] 2020-10-08 10:47
Hi @aditya-3008 , the error you are receiving because the component is not found. If you are sure that you are mentioning the `react-root` correctly in the [configuration file](https://github.com/abhinaba-ghosh/cypress-react-selector#wait-for-application-to-be-ready-to-run-tests), then the only reason is an exact match with the `props` is not found. It is like any other selection process. If you can provide a similar repository where I can reproduce the bug, it will be helpful. You don't need to have the access to the source code, but you need to know what the `react-toot` of the application. If the root is explicitly not provided, then `cypress-react`selector` automatically figure it out. Now, the problem is there can be multiple roots. In that case, you need to provide the target one. 
For a zoom jam, connect me [here](askabhinaba@gmail.com)

**Comment by aditya-3008** [comment] 2020-10-08 10:50
Can you share some example to find react-root of application, in my DOM I had 
<div id="root" class ="">

So I took this root and put it in my config file.  Do I need to take some other root for react, if yes how it will be.

**Comment by abhinaba-ghosh** [comment] 2020-10-08 10:59
**Root**: The parent where the object resides

<img width="1182" alt="Screenshot 2020-10-08 at 4 27 31 PM" src="https://user-images.githubusercontent.com/23141842/95450078-5963a380-0983-11eb-892c-375f0ee1f3dd.png">

**Component:**
![Uploading Screenshot 2020-10-08 at 4.26.19 PM.png…]()

**Comment by aditya-3008** [comment] 2020-10-08 11:32
I am using exactly the same syntax as per my application, but still, it is not able to find out. It is giving the same error.  I think my application is having complex components structure with a lot of Anonymous components. Can you share URL of some application so that I can try my hands if I am finding components correctly or not.

**Comment by aditya-3008** [comment] 2020-10-08 11:32
I am using exactly the same syntax as per my application, but still, it is not able to find out. It is giving the same error.  I think my application is having complex components structure with a lot of Anonymous components. Can you share URL of some application so that I can try my hands if I am finding components correctly or not.

**Comment by aditya-3008** [comment] 2020-10-08 11:33
I am using exactly the same syntax as per my application, but still, it is not able to find out. It is giving the same error.  I think my application is having complex components structure with a lot of Anonymous components. Can you share URL of some application so that I can try my hands if I am finding components correctly or not.

**Comment by abhinaba-ghosh** [comment] 2020-10-08 12:47
Can you check these [tests](https://github.com/abhinaba-ghosh/cypress-react-selector/blob/master/cypress/integration/calculator.spec.js)

**Comment by aditya-3008** [comment] 2020-10-08 13:50
Thank you, I tested these tests and have much clear understanding now. However, I was using correct pattern in my scripts maybe the component name in my application is not appropriate or something. I want to ask that can we use other tags like
{ props: { item: { label: 'email' }}}  as well instead of  " name: 'mail' " considering the above example.

**Comment by xshadowlegendx** [comment] 2020-10-08 15:18
hello, I also met this issue and I already made sure the root is found by setting non existence root which gave me root not found error and setting correct root which does not give me any error but when I try to use `cy.react` or `cy.getReact` it always through me the error

**Comment by abhinaba-ghosh** [comment] 2020-10-08 16:55
> Thank you, I tested these tests and have much clear understanding now. However, I was using correct pattern in my scripts maybe the component name in my application is not appropriate or something. I want to ask that can we use other tags like
> { props: { item: { label: 'email' }}} as well instead of " name: 'mail' " considering the above example.

@aditya-3008 you can use any of the props available for the target component.

**Comment by abhinaba-ghosh** [comment] 2020-10-08 16:58
@xshadowlegendx @aditya-3008 It seems like the issue is happening on a larger scale.  Using a production instance and not having the access to source code is a pain here. Would you guys mind sharing a private/public repository with some dummy codes and tests that you find difficult to construct? I can then give a proper look and re-constrcut the tests. I think in that way the learning will be complete from both the sides.

**Comment by abhinaba-ghosh** [comment] 2020-10-08 18:17
Guys, for a better understanding, you also pull down this [repository](https://github.com/abhinaba-ghosh/example-cypress-react-selector-formik) and play with it.

**Comment by aditya-3008** [comment] 2020-10-09 08:16
@xshadowlegendx  @abhinaba-ghosh  Yes it happens pn larger scale because I have tried with small basic react apps and it works fine but in real production sites it is not able to find any component using this pattern.

**Comment by abhinaba-ghosh** [comment] 2020-10-09 08:43
Hey @aditya-3008, sometimes in production environment React components get minified and changed their names. Kindly inspect the component names and props in production vs beta/stage environments. If components and props adhere to the same nomenclature, then there should be no problem to fetch the elements with `react-selector` identifiers. In case if you find there are deviations in the production instance, you can build the react app in [profiling mode](https://create-react-app.dev/docs/production-build/#profiling) to have the same component nomenclature.

**Comment by htd-tstepien** [comment] 2020-10-09 12:49
I have problem with finding my component too. I want just check if it exist. I have many buttons but Cypress can't find my TextButton with children prop "Today"

Code:
```
cy.getReact('TextButton', { props: { children: 'Today' } })
      .getProps('children')
      .should(prop => {
        expect(prop).to.eq('Today');
      });
```
Env:
![image](https://user-images.githubusercontent.com/57900160/95584698-6ee9d380-0a3e-11eb-9945-6d20589dd2db.png)

Output:
`Previous subject found null. getProps() is a child command. Use with cy.getReact()`

**Comment by abhinaba-ghosh** [comment] 2020-10-09 16:07
@htd-tstepien This is happening because the component `TextButton` is not loaded at the time of you run the operation. This will be fixed with https://github.com/abhinaba-ghosh/cypress-react-selector/issues/48

Meanwhile, add extra logic to load the component, then you execute the `getReact`. Something like:

```js
cy.react('TextButton').should('exists');

cy.getReact('TextButton', { props: { children: 'Today' } })
      .getProps('children')
      .should(prop => {
        expect(prop).to.eq('Today');
      });
```

Let me know if that solves the problem.

**Comment by aditya-3008** [comment] 2020-10-10 18:04
Hi , I am still not able to find the component. Please have a sample DOM look of my app.

![image](https://user-images.githubusercontent.com/69587843/95661953-c4ec7300-0b33-11eb-926f-31cd51f33d47.png)

**Comment by abhinaba-ghosh** [comment] 2020-10-10 18:16
Hey @aditya-3008, Can you be more specific? This is an interesting issue and I would like to understand which error it is throwing exactly. Can you try running the below code and inspect in cypress electron runner which exact error it is showing?

```js
cy.react('CatalogGridViewToggleBase', { props: { item: { name: 'abc' } } }).should('exist');
```
Side note, `getReact` returns an [RESQ node](https://github.com/abhinaba-ghosh/cypress-react-selector/blob/36e336a24e64c7d6e9e92dd08896a914903d504f/index.d.ts#L4) where `react` returns the DOM element.

**Comment by aditya-3008** [comment] 2020-10-11 09:27
@abhinaba-ghosh - Issue is still the same, component not found. There can be multiple reasons for it.

  > Check the root is defined as a env parameter (cypress.json config file).

  > If the root is defined correctly, check other parameters - component name, props and state objects.

For your more understanding, let say we have multiple components with name CatalogGridViewToggleBase as tiles but we are giving the props name abc which is only one, I think the above code should work or do we have to follow other pattern to find a component which is having common name on the page but each of their props have different names. 
Because other child objects are also having same name i.e. CatalogGridViewToggleBase but inside its prop the name will be let say xyz. So I explained you scenario now what do you think the pattern of finding is correct or any other suggestion

**Comment by abhinaba-ghosh** [comment] 2020-10-11 10:33
@aditya-3008 can you share a repository where I can reproduce the issue?

**Comment by abhinaba-ghosh** [comment] 2020-10-11 21:06
Hi @aditya-3008 @xshadowlegendx @htd-tstepien Please upgrade to `v2.1.0` and check if your issue gets resolved. I have added some fluent retry mechanism. If the issue is asynchronous loading, then this version will help you tremendously.

**Comment by maga-polito** [comment] 2020-10-12 15:18
I'm having the same issues on tests that used to work no it seems like it can find any component even if the cypress-react-selector is loaded correctly, now if I try to wait for component existance it gives me following 
error {timeout: 30100}, function(){}
Could not find instance of React in given element

**Comment by abhinaba-ghosh** [comment] 2020-10-12 17:20
@maga-polito I think the error it is throwing is correct. Make sure the component you are searching should fall under the root you are specifying. I highly suggest going through a couple of projects that use the react-selector mentioned [here](https://github.com/abhinaba-ghosh/cypress-react-selector#community-projects). This library requires some understanding of how the app is built. Feel free to chat with me in Gitter if you need some assistance.

**Comment by htd-tstepien** [comment] 2020-10-27 10:55
> @htd-tstepien This is happening because the component `TextButton` is not loaded at the time of you run the operation. This will be fixed with #48
> 
> Meanwhile, add extra logic to wait until the component gets loaded, then you execute the `getReact`. Something like:
> 
> ```js
> cy.react('TextButton').should('exists');  // retries until existence 
> 
> cy.getReact('TextButton', { props: { children: 'Today' } })
>       .getProps('children')
>       .should(prop => {
>         expect(prop).to.eq('Today');
>       });
> ```
> 
> Let me know if that solves the problem.

Hey @abhinaba-ghosh , sorry for the late response. Still without a result.
```js
    cy.react('TextButton').should('exist');

    cy.getReact('TextButton', { props: { children: 'Today' } })
      .getProps('children')
      .should(prop => {
        expect(prop).to.eq('Today');
      });
```

And I've got
<img width="490" alt="image" src="https://user-images.githubusercontent.com/57900160/97292257-4ee24e80-184b-11eb-9a4a-883ee80c936e.png">

**Comment by abhinaba-ghosh** [comment] 2020-10-27 11:02
@htd-tstepien now this is something interesting. Can you share a repository where I can reproduce the issue? Feel free to connect with me in `Gitter`.

**Comment by htd-tstepien** [comment] 2020-10-27 12:54
hmm, it'll be hard because it's a private project and I wanted to test this module if it can fit into our tech stack to simplify tests and expand possibilities 😕 I will keep an eye on the development of this module because it is promising, but it is a little bit incomprehensible to me to keep it in this situation.

**Comment by abhinaba-ghosh** [comment] 2020-10-27 19:29
Sure @htd-tstepien. btw, are you running the tests with the raw components or you are using a production build of the application?

**Comment by htd-tstepien** [comment] 2020-10-27 19:35
1. Raw
2. Yes it works on other components

**Comment by abhinaba-ghosh** [comment] 2020-10-27 19:52
> 1. Raw
> 2. Yes it works on other components

@htd-tstepien Good to know that it works with other components. Now specifically check if this component falls under different react roots or not. Sometimes apps do have different roots. If this is the case, then you can explicitly pass the root as:

```js
cy.react('TextButton', {root:"#other-root"}).should('exists');
```

**Comment by abhinaba-ghosh** [comment] 2020-11-03 20:40
Closing this thread. This is an error that can be caused for multiple reasons. If anyone gets the same, raise a separate ticket with a proper code example.

**Closed by abhinaba-ghosh** 2020-11-03 20:40 UTC
Labels: discussion

**Comment by drecali** [comment] 2022-02-23 05:44
Thank you @abhinaba-ghosh for the advice below (and of course for maintaining such a useful plugin 🙏 )! My tests were passing locally in `headless` and `headed` mode, but `cy.react()` could never find the right components in the deployed version. In case it helps others, I'll include a comparison of how different my component names were.

> ...sometimes in production environment React components get minified and changed their names...

| Local | Deploy |
|--|--|
| ![image](https://user-images.githubusercontent.com/24983797/155267198-6d56c3da-5bc0-41fb-b69e-b9d50b2dd750.png) | ![image](https://user-images.githubusercontent.com/24983797/155267285-f0f61c01-0c24-46a4-8ca1-338b45a7dfff.png) |

**Comment by abhinaba-ghosh** [comment] 2022-02-23 06:07
Hi @drecali you can try this solution - https://stackoverflow.com/a/69760307
